export default function decorate(block) {
  // block = complete Video block DOM generated by EDS.
  //
  // Example before decoration:
  //
  // <div class="video block">
  //   <div>
  //     <div>
  //       <p>
  //         <a href="https://www.youtube.com/watch?v=VIDEO_ID">
  //           https://www.youtube.com/watch?v=VIDEO_ID
  //         </a>
  //       </p>
  //     </div>
  //   </div>
  // </div>


  const link = block.querySelector('a');

  // Find the first anchor tag inside the Video block.
  //
  // Example value:
  //
  // link =
  // <a href="https://www.youtube.com/watch?v=VIDEO_ID">
  //   https://www.youtube.com/watch?v=VIDEO_ID
  // </a>


  if (!link) return;

  // Safety check.
  //
  // If no link exists inside the block,
  // stop the function here.


  const url = link.href;

  // Get the actual URL from the link.
  //
  // Example:
  //
  // url =
  // "https://www.youtube.com/watch?v=abc123"


  const videoId = getYouTubeVideoId(url);

  // Call our helper function.
  //
  // Example:
  //
  // url =
  // https://www.youtube.com/watch?v=abc123
  //
  // videoId =
  // abc123


  if (!videoId) return;

  // If we cannot find a valid YouTube video ID,
  // stop here.


  const wrapper = document.createElement('div');

  // Creates:
  //
  // <div></div>


  wrapper.classList.add('video-wrapper');

  // Becomes:
  //
  // <div class="video-wrapper"></div>


  const iframe = document.createElement('iframe');

  // Creates:
  //
  // <iframe></iframe>


  iframe.src = `https://www.youtube.com/embed/${videoId}`;

  // Example:
  //
  // videoId = abc123
  //
  // iframe.src becomes:
  //
  // https://www.youtube.com/embed/abc123


  iframe.title = 'Video player';

  // Adds an accessible title.
  //
  // Result:
  //
  // <iframe title="Video player">


  iframe.allow =
    'accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture';

  // Tells the browser which features
  // this embedded YouTube player is allowed to use.


  iframe.allowFullscreen = true;

  // Allows user to open the video fullscreen.


  iframe.loading = 'lazy';

  // Browser does not need to load the iframe immediately
  // if it is far below the viewport.
  //
  // This can help page performance.


  wrapper.append(iframe);

  // Put iframe inside our wrapper.
  //
  // Now:
  //
  // <div class="video-wrapper">
  //   <iframe></iframe>
  // </div>


  block.textContent = '';

  // Remove the original authored URL from the block.
  //
  // Before:
  //
  // block
  // └── original URL
  //
  // After:
  //
  // block
  // └── empty


  block.append(wrapper);

  // Add our new video player.
  //
  // Final structure:
  //
  // <div class="video block">
  //
  //   <div class="video-wrapper">
  //
  //     <iframe
  //       src="https://www.youtube.com/embed/abc123"
  //       title="Video player"
  //       loading="lazy"
  //     ></iframe>
  //
  //   </div>
  //
  // </div>
}


// Helper function.
// Its only job is to extract the YouTube video ID
// from different YouTube URL formats.
function getYouTubeVideoId(url) {
  // url example:
  //
  // https://www.youtube.com/watch?v=abc123


  const parsedUrl = new URL(url);

  // Convert the URL string into a URL object.
  //
  // Now we can easily read things like:
  //
  // parsedUrl.hostname
  // parsedUrl.pathname
  // parsedUrl.searchParams


  if (parsedUrl.hostname.includes('youtu.be')) {
    // Short YouTube URL example:
    //
    // https://youtu.be/abc123
    //
    // pathname =
    // /abc123

    return parsedUrl.pathname.slice(1);

    // slice(1) removes the first "/"
    //
    // /abc123
    // becomes
    // abc123
  }


  if (parsedUrl.hostname.includes('youtube.com')) {
    // Normal YouTube URL:
    //
    // https://www.youtube.com/watch?v=abc123


    return parsedUrl.searchParams.get('v');

    // searchParams.get('v')
    // reads:
    //
    // ?v=abc123
    //
    // and returns:
    //
    // abc123
  }


  return null;

  // If URL is not recognized as YouTube,
  // return null.
}
