export default function decorate(block) {
  // block = complete CTA block DOM generated by EDS.
  //
  // Example:
  //
  // <div class="cta block">
  //   <div>
  //     <div>
  //       <p>Build real projects and learn by doing.</p>
  //     </div>
  //   </div>
  //
  //   <div>
  //     <div>
  //       <p>
  //         <a href="#courses">Start Learning</a>
  //       </p>
  //     </div>
  //   </div>
  // </div>


  const link = block.querySelector('a');

  // Find the CTA link inside the block.
  //
  // Example:
  //
  // link =
  // <a href="#courses">Start Learning</a>


  if (link) {
    // Only run this code if a link exists.


    link.classList.add('cta-button');

    // Add our custom class.
    //
    // Before:
    //
    // <a href="#courses">
    //   Start Learning
    // </a>
    //
    // After:
    //
    // <a
    //   href="#courses"
    //   class="cta-button"
    // >
    //   Start Learning
    // </a>
  }


  const paragraphs = block.querySelectorAll('p');

  // Find every paragraph inside the CTA.
  //
  // Example:
  //
  // paragraphs[0]
  // = Build real projects and learn by doing.
  //
  // paragraphs[1]
  // = Start Learning link paragraph


  paragraphs.forEach((paragraph) => {
    // Loop through every paragraph.


    if (!paragraph.querySelector('a')) {
      // If this paragraph does NOT contain a link,
      // treat it as normal CTA text.


      paragraph.classList.add('cta-text');

      // Example:
      //
      // <p class="cta-text">
      //   Build real projects and learn by doing.
      // </p>
    }
  });
}